export const LoginActionTypes = {
    LOAD_AUTHORIZATION_START: '[Authorization] LOAD_AUTHORIZATION_START',
    LOAD_AUTHORIZATION_PROCESS: '[Authorization] LOAD_AUTHORIZATION_PROCESS',
    LOAD_AUTHORIZATION_SUCCESS: '[Authorization] LOAD_AUTHORIZATION_SUCCESS',
    LOAD_AUTHORIZATION_ERROR: '[Authorization] LOAD_AUTHORIZATION_ERROR',

    LOAD_REGISTRATION_START: '[Registration] LOAD_REGISTRATION_START',
    LOAD_REGISTRATION_SUCCESS: '[Registration] LOAD_REGISTRATION_SUCCESS',
    LOAD_REGISTRATION_ERROR: '[Registration] LOAD_REGISTRATION_ERROR',

    LOGOUT: '[Authorization] LOGOUT'
} as const;