export const LoginActionTypes = {
    LOAD_AUTHORIZATION_START: '[Authorization] LOAD_AUTHORIZATION_START',
    LOAD_AUTHORIZATION_PROCESS: '[Authorization] LOAD_AUTHORIZATION_PROCESS',
    LOAD_AUTHORIZATION_SUCCESS: '[Authorization] LOAD_AUTHORIZATION_SUCCESS',
    LOAD_AUTHORIZATION_ERROR: '[Authorization] LOAD_AUTHORIZATION_ERROR',
    LOGOUT: '[Authorization] LOGOUT'
} as const;