export const CategoryActionTypes = {
    LOAD_CATEGORY_START: '[Category] LOAD_CATEGORY_START',
    LOAD_CATEGORY_SUCCESS: '[Category] LOAD_CATEGORY_SUCCESS',
    LOAD_CATEGORY_ERROR: '[Category] LOAD_CATEGORY_ERROR',

    CREATE_CATEGORY_START: '[Category] CREATE_CATEGORY_START',
    CREATE_CATEGORY_SUCCESS: '[Category] CREATE_CATEGORY_SUCCESS',
    CREATE_CATEGORY_ERROR: '[Category] CREATE_CATEGORY_ERROR',

    DELETE_CATEGORY: '[Category] DELETE_CATEGORY'
} as const;