export const ProductsActionTypes = {
    LOAD_PRODUCTS_START: '[Products] LOAD_PRODUCTS_START',
    LOAD_ALL_PRODUCTS_START: '[Products] LOAD_ALL_PRODUCTS_START',
    LOAD_PRODUCTS_SUCCESS: '[Products] LOAD_PRODUCTS_SUCCESS',
    LOAD_PRODUCTS_ERROR: '[Products] LOAD_PRODUCTS_ERROR',

    LOAD_PRODUCT_START: '[Products] LOAD_PRODUCT_START',
    LOAD_PRODUCT_SUCCESS: '[Products] LOAD_PRODUCT_SUCCESS',
    LOAD_PRODUCT_ERROR: '[Products] LOAD_PRODUCT_ERROR',

    SET_VIEW: '[Products] SET_VIEW',

    CREATE_PRODUCT_START: '[Products] CREATE_PRODUCT_START',
    CREATE_PRODUCT_SUCCESS: '[Products] CREATE_PRODUCT_SUCCESS',
    CREATE_PRODUCT_ERROR: '[Products] CREATE_PRODUCT_ERROR',

    REMOVE_PRODUCT: '[Products] REMOVE_PRODUCT',
    DELETE_PRODUCT: '[Products] DELETE_PRODUCT',

    SET_PAGE: '[Pagination] SET_PAGE'
} as const;